#!/usr/bin/env bash
# =============================================================================
# enumerate.sh — enumerate all Python packages on Chainguard Libraries
#                and write a pip-compatible requirements.txt
# =============================================================================
# Runs on the LOWSIDE (connected) machine.
#
# Queries the PEP 503 simple index at libraries.cgr.dev — the same endpoint
# pip uses — so the output reflects exactly what is available for download.
# One package name per line, ready for collect.sh.
#
# Prerequisites:
#   ~/.netrc must contain credentials for libraries.cgr.dev (same as collect.sh)
#
# Usage:
#   ./enumerate.sh [output-file]
#
# Defaults:
#   output-file   requirements.txt (written next to this script)
#
# Example:
#   ./enumerate.sh
#   ./collect.sh requirements.txt
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

OUTPUT="${1:-${SCRIPT_DIR}/requirements.txt}"

verify_netrc

command -v curl >/dev/null || { echo "ERROR: curl not found on PATH" >&2; exit 1; }

echo "=== enumerate.sh ==="
echo "Index  : ${CG_PYTHON_INDEX}"
echo "Output : ${OUTPUT}"
echo ""
echo "Fetching package list ..."

{
  echo "# Generated by enumerate.sh on $(date -u +%Y-%m-%d)"
  echo "# Source: ${CG_PYTHON_INDEX}"
  echo ""
} > "$OUTPUT"

extract_packages() {
  python3 - <<'PY'
import sys, html.parser

class LinkParser(html.parser.HTMLParser):
    def handle_starttag(self, tag, attrs):
        if tag == "a":
            for k, v in attrs:
                if k == "href" and v:
                    # href may be absolute (/simple/numpy/) or relative (numpy/)
                    pkg = v.rstrip("/").split("/")[-1]
                    if pkg:
                        print(pkg)

LinkParser().feed(sys.stdin.read())
PY
}

curl --netrc --silent --fail "$CG_PYTHON_INDEX" \
  | extract_packages \
  | sort -u \
  >> "$OUTPUT"

PKG_COUNT=$(grep -c '^[^#[:space:]]' "$OUTPUT" || true)

echo "Packages : ${PKG_COUNT}"
echo ""
echo "Run collect.sh to download all packages:"
echo "  ./collect.sh ${OUTPUT}"
