#!/usr/bin/env bash
# =============================================================================
# libraries-list.sh — enumerate all Python packages on Chainguard Libraries
#                     and write a pip-compatible requirements.txt
# =============================================================================
# Runs on the LOWSIDE (connected) machine.
#
# Queries the PEP 503 simple index at libraries.cgr.dev — the same endpoint
# pip uses — so the output reflects exactly what is available for download.
# One package name per line, ready for collect.sh.
#
# Prerequisites:
#   ~/.netrc must contain credentials for libraries.cgr.dev (same as collect.sh)
#
# Usage:
#   ./libraries-list.sh [output-file]
#
# Defaults:
#   output-file   requirements.txt (written next to this script)
#
# Example:
#   ./libraries-list.sh
#   ./collect.sh requirements.txt
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${1:-${SCRIPT_DIR}/requirements.txt}"

# Verify ~/.netrc has an entry for libraries.cgr.dev
python3 - <<'PY'
import netrc, sys
try:
    entry = netrc.netrc().authenticators("libraries.cgr.dev")
except FileNotFoundError:
    entry = None
if not entry:
    print("ERROR: no credentials for libraries.cgr.dev in ~/.netrc", file=sys.stderr)
    print("", file=sys.stderr)
    print("Add them with:", file=sys.stderr)
    print("  chainctl auth pull-token create --repository=python --ttl=8760h", file=sys.stderr)
    print("  # Then append to ~/.netrc:", file=sys.stderr)
    print("  machine libraries.cgr.dev", file=sys.stderr)
    print("  login    <username>", file=sys.stderr)
    print("  password <password>", file=sys.stderr)
    print("  chmod 600 ~/.netrc", file=sys.stderr)
    sys.exit(1)
PY

command -v curl >/dev/null || { echo "ERROR: curl not found on PATH" >&2; exit 1; }

CG_PYTHON_INDEX="https://libraries.cgr.dev/python/simple/"

echo "=== libraries-list.sh ==="
echo "Index  : ${CG_PYTHON_INDEX}"
echo "Output : ${OUTPUT}"
echo ""
echo "Fetching package list ..."

# Write file header
{
  echo "# Generated by libraries-list.sh on $(date -u +%Y-%m-%d)"
  echo "# Source: ${CG_PYTHON_INDEX}"
  echo ""
} > "$OUTPUT"

# Fetch the PEP 503 simple index and extract package names.
# The root /simple/ page contains one <a href="/simple/<name>/"> per package.
extract_packages() {
  python3 - <<'PY'
import sys, html.parser

class LinkParser(html.parser.HTMLParser):
    def handle_starttag(self, tag, attrs):
        if tag == "a":
            for k, v in attrs:
                if k == "href" and v:
                    # href may be absolute (/simple/numpy/) or relative (numpy/)
                    pkg = v.rstrip("/").split("/")[-1]
                    if pkg:
                        print(pkg)

LinkParser().feed(sys.stdin.read())
PY
}

curl --netrc --silent --fail "$CG_PYTHON_INDEX" \
  | extract_packages \
  | sort -u \
  >> "$OUTPUT"

PKG_COUNT=$(grep -c '^[^#[:space:]]' "$OUTPUT" || true)

echo "Packages : ${PKG_COUNT}"
echo ""
echo "Run collect.sh to download all packages:"
echo "  ./collect.sh ${OUTPUT}"
